toDoList/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "auth"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
]

toDoList/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"todolists", views.TodoListViewSet)
router.register(r"todos", views.TodoViewSet)

app_name = "api"
urlpatterns = [
    path("", include(router.urls)),
]

toDoList/todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("lists.urls")),
    path("auth/", include("accounts.urls")),
    path("api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("admin/", admin.site.urls),
]

toDoList/accounts/models.py
from django.db import models

# Create your models here.

toDoList/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


def widget_attrs(placeholder):
    return {"class": "u-full-width", "placeholder": placeholder}


def form_kwargs(widget, label="", max_length=64):
    return {"widget": widget, "label": label, "max_length": max_length}


class LoginForm(forms.Form):

    username = forms.CharField(
        **form_kwargs(widget=forms.TextInput(attrs=widget_attrs("Username")))
    )
    password = forms.CharField(
        **form_kwargs(widget=forms.PasswordInput(attrs=widget_attrs("Password")))
    )

    def clean(self):
        # Don't check if we already have errors.
        if self.errors:
            return self.cleaned_data

        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = User.objects.filter(username=username).first()

        if not user or not user.check_password(password):
            raise forms.ValidationError("Incorrect username and/or password.")

        return self.cleaned_data


class RegistrationForm(forms.Form):

    username = forms.CharField(
        **form_kwargs(widget=forms.TextInput(attrs=widget_attrs("Username")))
    )

    email = forms.EmailField(
        **form_kwargs(widget=forms.TextInput(attrs=widget_attrs("Email")))
    )

    password = forms.CharField(
        **form_kwargs(widget=forms.PasswordInput(attrs=widget_attrs("Password")))
    )

    password_confirmation = forms.CharField(
        **form_kwargs(
            widget=forms.PasswordInput(attrs=widget_attrs("Password confirmation"))
        )
    )

    def clean(self):
        password = self.cleaned_data.get("password")
        password_confirmation = self.cleaned_data.get("password_confirmation")

        if password and password != password_confirmation:
            raise forms.ValidationError("Passwords don't match.")

        return self.cleaned_data

toDoList/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from accounts.forms import LoginForm, RegistrationForm
from lists.forms import TodoForm


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=request.POST["username"], password=request.POST["password"]
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("lists:index")
        else:
            return render(request, "accounts/login.html", {"form": form})
    else:
        return render(request, "accounts/login.html", {"form": LoginForm()})

    return redirect("lists:index")


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                username=request.POST["username"],
                email=request.POST["email"],
                password=request.POST["password"],
            )
            return redirect("auth:login")
        else:
            return render(request, "accounts/register.html", {"form": form})
    else:
        return render(request, "accounts/register.html", {"form": RegistrationForm()})


def logout_view(request):
    logout(request)
    return redirect("lists:index")

toDoList/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block body %}
<section class="header">
  <h2 class="title">Login</h2>
  <div class="row">
    <div class="three columns value-prop"></div>
    <div class="six columns">
      <form method=post>
        {% csrf_token %}
        <dl>
          <dd>{{ form }}
          <dt><input type="submit" class="button button-primary" value="Login">
        </dl>
      </form>
      <p>New user? <a href="{% url 'auth:register' %}">Click here to register</a>.</p>
    </div>
  </div>
</section>
{% endblock %}

toDoList/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block body %}
<section class="header">
  <h2 class="title">Register</h2>
  <div class="row">
    <div class="three columns value-prop"></div>
    <div class="six columns">
      <form method=post>
        {% csrf_token %}
        <dl>
          <dd>{{ form }}
          <dt><input type="submit" class="button button-primary" value="Register">
        </dl>
      </form>
      <p>Already registerd? <a href="{% url 'auth:login' %}">Click here to login</a>.</p>
    </div>
  </div>
</section>
{% endblock %}